### ISSUE TITLE
Change shortcut?

### ISSUE THREAD

**Issue by Baze-cmd** [eggnstone/DartFormatJetbrainsPlugin#113]
Is it possible to change format shortcut to Ctrl+Alt+L, that is the default IntiliJ one that does "dart format" style will there be a confilict there?

**Comment by eggnstone** [comment]
There will be a conflict and also you may want to keep using formatting other languages with the built-in formatter.
But you can define the shortcut yourself.
I don't know how exactly from the top of my head so please see the documentation.

**Comment by eggnstone** [comment]
Ctrl+Alt+L is now the default, too.
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
