### ISSUE TITLE
Failed to start external dart_format: Cannot find the dart_format package: File does not exist at expected location: C:\Users\davro\AppData\Local\Pub\Cache\bin\dart_format.bat

### ISSUE THREAD

**Issue by SHexrozDavronov** [eggnstone/DartFormatJetbrainsPlugin#18]
Please supply any additional information here, e.g. the source code that caused the error:

OS: Windows 11

**Comment by eggnstone** [comment]
Hi.
Did you install the dart_format package from pub.dev?
Just call `dart pub global activate dart_format`.
Then dart_format on the command line should work. Does it?
Then it should work inside the IDE, too.
