### ISSUE TITLE
Failed to start external dart_format: Cannot find the dart_format package: File does not exist at expected location: ~/.pub-cache/bin/dart_format.sh

### ISSUE THREAD

**Issue by chau-thanh-nhan** [eggnstone/DartFormatJetbrainsPlugin#28]
Sorry, i tried this https://pub.dev/packages/dart_format/install
but still not resolved.

plz, help me.

OS: Mac OS X

**Comment by eggnstone** [comment]
Can you check that path (~/.pub-cache/bin/) ?
Does it contain a dart_format file without an extension?
Is the dart_format file a binary or a shell script?
I will adjust my plugin accordingly but in the meantime please try copying the dart_format file to dart_format.sh and if this does not work then maybe create a dart_format.sh with the following content that I hope works:

#!/bin/sh
~/.pub-cache/bin/dart_format

**Comment by eggnstone** [comment]
Did my explanation help?
Does it work now?

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
