### ISSUE TITLE
IntelliJ Version Compatibility

### ISSUE THREAD

**Issue by SteveBraich** [eggnstone/DartFormatJetbrainsPlugin#4]
What Version of IntelliJ is this compatible with?

![image](https://github.com/eggnstone/DartFormatJetbrainsPlugin/assets/108843078/5c862eb4-11e0-4591-be70-4ac2d5342666)

**Comment by eggnstone** [comment]
Hi. I'm currently working on a complete rebuild.
It wasn't ready for the public yet, I was too hasty. 
Therefore it is now disabled/unpublished.
I'm working on getting it was soon.
I'll respond here when it's ready.

**Comment by eggnstone** [comment]
Done
