### ISSUE TITLE
Timeout while waiting for external dart_format.

### ISSUE THREAD

**Issue by mohammed-haimour** [eggnstone/DartFormatJetbrainsPlugin#43]
could you please help me 
when use dartFormat package the whole IDE gets freezed 

### **ERROR INFO ::**

Origin: FormatAction.formatOrReport/1
OS: Mac OS X
Plugin version: 2.0.8
External dart_format version: <unknown version>

<img width="425" alt="Screenshot 2024-04-12 at 6 03 05 PM" src="https://github.com/eggnstone/DartFormatJetbrainsPlugin/assets/135971016/a71ed5d0-816d-429b-9707-a233a926bc2e">

**Comment by eggnstone** [comment]
Can you restart the IDE? Does this help?

If not, please 
- check if the environment variable "temp" is set
- attach the following log files from your "temp" directory:
  - dart_format_*.log
  - DartFormatPlugin_*.log

**Comment by eggnstone** [comment]
I think the reason may be that under macOS the environment variable isn't "TEMP", but "TMPDIR".
Can you set $TEMP to "/tmp" and restart the IDE?

**Comment by mohammed-haimour** [comment]
thanks... now it's working

**Comment by yfming93** [comment]
> I think the reason may be that under macOS the environment variable isn't "TEMP", but "TMPDIR". Can you set $TEMP to "/tmp" and restart the IDE?

How to set it ? Please show me a picture. 3Q. The picture for How-to-set/Where-to-set/What-code-to-set.

**Comment by eggnstone** [comment]
> > I think the reason may be that under macOS the environment variable isn't "TEMP", but "TMPDIR". Can you set $TEMP to "/tmp" and restart the IDE?
> 
> How to set it under macOS ? Please show me a picture. 3Q. The picture for How-to-set/Where-to-set/What-code-to-set.

You don't need to set "TEMP".
Under macOS the plugin now uses the proper "TMPDIR", so that problem should be resolved for macOS users.

"To list all the environment variables, use the command "env" (or "printenv"). You could also use "set" to list all the variables, including all local variables."
https://www3.ntu.edu.sg/home/ehchua/programming/howto/Environment_Variables.html#zz-3.

**Comment by yfming93** [comment]
> > > I think the reason may be that under macOS the environment variable isn't "TEMP", but "TMPDIR". Can you set $TEMP to "/tmp" and restart the IDE?
> > 
> > 
> > How to set it under macOS ? Please show me a picture. 3Q. The picture for How-to-set/Where-to-set/What-code-to-set.
> 
> You don't need to set "TEMP". Under macOS the plugin now uses the proper "TMPDIR", so that problem should be resolved for macOS users.
> 
> "To list all the environment variables, use the command "env" (or "printenv"). You could also use "set" to list all the variables, including all local variables." [www3.ntu.edu.sg/home/ehchua/programming/howto/Environment_Variables.html#zz-3](https://www3.ntu.edu.sg/home/ehchua/programming/howto/Environment_Variables.html#zz-3).

When I press Command+Alt+, under MacOS . The "Timeout while waiting for external dart_format" error show again. 
Plugin : 2.0.9.
MacOs Sonoma：14.4.1 (23E224)
Android Studio：Android Studio Jellyfish | 2023.3.1 Patch 1

![image](https://github.com/eggnstone/DartFormatJetbrainsPlugin/assets/18211498/4b20e7c6-49b0-4866-bc2d-560035035cdf)
