### ISSUE TITLE
Timeout while waiting for external dart_format.

### ISSUE THREAD

**Issue by dhimu** [eggnstone/DartFormatJetbrainsPlugin#48]
Please supply any additional information here, e.g. the source code that caused the error:

Origin: FormatAction.formatOrReport/1
OS: Mac OS X
Plugin version: 2.0.9
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
Can you restart the IDE? Does this help?

If not, please
- check if the environment variable "TMPDIR" is set
- attach the following log files from your "TMPDIR" directory:
  - dart_format_*.log
  - DartFormatPlugin_*.log
