### ISSUE TITLE
Cannot run program "dart_format": error=2, No such file or directory

### ISSUE THREAD

**Issue by Nkm13** [eggnstone/DartFormatJetbrainsPlugin#5]
Please supply any additional information here, e.g. the source code that caused the error:

```
java.io.IOException: Cannot run program "dart_format": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat$run$process$1.invokeSuspend(ExternalDartFormat.kt:87
```

**Comment by eggnstone** [comment]
Did you install the dart_format package?
Please look here: https://pub.dev/packages/dart_format/install
Does the error still occur?

**Comment by staginghub** [comment]
I get the same error, but solved it by installing dart_format.  Could you add this line to the installation instructions:
'dart pub global activate dart_format'
Thanks

**Comment by Nkm13** [comment]
I have try 'dart pub global activate dart_format' and install the dart_format package but the error still occur

**Comment by eggnstone** [comment]
@staginghub Thank you! I will!

**Comment by eggnstone** [comment]
@Nkm13 
- Does calling ```dart_format``` from the command line / DOS box / bash work (i.e, does it start the dart_format program, or still "No such file or directory"?)
- Which operation system do you use?

**Comment by eggnstone** [comment]
@Nkm13 
@staginghub 
Please check the latest version (2.5) of the DartFormat plugin:
https://plugins.jetbrains.com/plugin/21003-dartformat/versions
This one should fix the problem or at least give better diagnostics.

**Comment by eggnstone** [comment]
Please reopen if the error still occurs.
