### ISSUE TITLE
Failed to start external dart_format: Cannot find the dart_format package: File does not exist at expected location: ~/.pub-cache/bin/dart_format[.sh]

### ISSUE THREAD

**Issue by codethinki** [eggnstone/DartFormatJetbrainsPlugin#59]
Please supply any additional information here, e.g. the source code that caused the error:

OS: Mac OS X
Plugin version: 2.0.9
External dart_format version: <unknown version>

I have installed this package (and activated it) and can execute the command "~/.pub-cache/bin/dart_format" perfectly fine via the shell when i cd to my project dir.

**Comment by eggnstone** [comment]
Can you restart the IDE? Does this help?

If not, please
- check if the environment variable "TMPDIR" is set
- attach the following log files from your "TMPDIR" directory:
  - dart_format_*.log
  - DartFormatPlugin_*.log

**Comment by codethinki** [comment]
i restarted the mac multiple times, so that cant be it. 
i've set the TEMPDIR variable now but i'm still facing the same error

**Comment by codethinki** [comment]
also your extension doesnt write to the tempdir

**Comment by eggnstone** [comment]
Under macOS the standard seems to be TMPDIR, not TEMPDIR.
Can you verify please?
