### ISSUE TITLE
Allow the users to configure the shortcut key for reformatting.

### ISSUE THREAD

**Issue by eggnstone** [eggnstone/DartFormatJetbrainsPlugin#6]
One other suggestion is to allow the users to configure the shortcut key for reformatting.  
This could make it a seamless transition from the existing Intellij reformatting shortcut.

(split from other issue: #3)

**Comment by eggnstone** [comment]
I didn't want to overwrite the default CTRL-ALT-L because DartFormat only formats Dart.
But you can assign an additional shortcut yourself in the IDE settings (please see below).
Is this OK or do you have a better suggestion without disabling the default formatter?

![AndroidStudioSettingsKeymap1](https://github.com/eggnstone/DartFormatJetbrainsPlugin/assets/11562425/09636d7a-a993-4952-a658-415f5439d2f1)
![AndroidStudioSettingsKeymap2](https://github.com/eggnstone/DartFormatJetbrainsPlugin/assets/11562425/0b80ba83-2bd5-4f23-a016-0e5392a30dc4)
![AndroidStudioSettingsKeymap3](https://github.com/eggnstone/DartFormatJetbrainsPlugin/assets/11562425/ddc4bb46-d8d1-4cfa-b14a-fdf24481b2af)
![AndroidStudioSettingsKeymap4](https://github.com/eggnstone/DartFormatJetbrainsPlugin/assets/11562425/e505aeff-f490-4669-b385-d93667b3fed7)
![AndroidStudioSettingsKeymap5](https://github.com/eggnstone/DartFormatJetbrainsPlugin/assets/11562425/b12cc077-a9ae-4ef6-a92b-0db445b686a7)

**Comment by eggnstone** [comment]
@staginghub does the solution above work for you?

**Comment by staginghub** [comment]
Hi, yes, this works for me.  thanks
