### ISSUE TITLE
Timeout while waiting for external dart_format.

### ISSUE THREAD

**Issue by eggnstone** [eggnstone/DartFormatJetbrainsPlugin#64]
Copied from other - closed - bug:

              > > > I think the reason may be that under macOS the environment variable isn't "TEMP", but "TMPDIR". Can you set $TEMP to "/tmp" and restart the IDE?
> > 
> > 
> > How to set it under macOS ? Please show me a picture. 3Q. The picture for How-to-set/Where-to-set/What-code-to-set.
> 
> You don't need to set "TEMP". Under macOS the plugin now uses the proper "TMPDIR", so that problem should be resolved for macOS users.
> 
> "To list all the environment variables, use the command "env" (or "printenv"). You could also use "set" to list all the variables, including all local variables." [www3.ntu.edu.sg/home/ehchua/programming/howto/Environment_Variables.html#zz-3](https://www3.ntu.edu.sg/home/ehchua/programming/howto/Environment_Variables.html#zz-3).

When I press Command+Alt+, under MacOS . The "Timeout while waiting for external dart_format" error show again. 
Plugin Version : 2.0.9.
MacOs Sonoma Version：14.4.1 (23E224)
Android Studio Version：Android Studio Jellyfish | 2023.3.1 Patch 1

![image](https://github.com/eggnstone/DartFormatJetbrainsPlugin/assets/18211498/4b20e7c6-49b0-4866-bc2d-560035035cdf)

_Originally posted by @yfming93 in https://github.com/eggnstone/DartFormatJetbrainsPlugin/issues/43#issuecomment-2151246733_

**Comment by shinriyo** [comment]
Same problem.
infinity while loop?

**Comment by eggnstone** [comment]
Please check if the environment variable `temp` on Windows / `tmpdir` on macOS is set.

Attach the following log files from your temp directory:
- dart_format_*.log
- DartFormatPlugin_*.log

**Comment by eggnstone** [comment]
Please try the latest version of the plugin:
https://plugins.jetbrains.com/plugin/21003-dartformat/edit/versions/stable/573377
Does it work now?
