### ISSUE TITLE
External dart_format: Expected connection details in JSON but received plain text.

### ISSUE THREAD

**Issue by kawengo10** [eggnstone/DartFormatJetbrainsPlugin#69]
Please supply any additional information here, e.g. the source code that caused the error:

```
StdErr: Can't load Kernel binary: Invalid kernel binary format version.
Did you install the dart_format package?
Basically just execute this:<pre>dart pub global activate dart_format</pre>
```
OS: Windows 11
Plugin version: 2.0.9
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
Please try the latest version of the plugin:
https://plugins.jetbrains.com/plugin/21003-dartformat/edit/versions/stable/573377
Does it work now?

**Comment by eggnstone** [comment]
Please try the latest version (2.0.15).
If it still occurs, then
- exit the IDE
- attached the latest dartformat log files from your temp directory (%TEMP% or C:\Temp or /temp or /tmp)

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
