### ISSUE TITLE
Failed to start external dart_format: Cannot find the dart_format package: File does not exist at expected location: ~/.pub-cache/bin/dart_format[.sh]

### ISSUE THREAD

**Issue by sdooweloc** [eggnstone/DartFormatJetbrainsPlugin#73]
Please supply any additional information here, e.g. the source code that caused the error:

Ran `dart pub global activate dart_format`
Confirmed both `dart_format` and `dartformat` are present under `~/.pub-cache/bin/`
Running `dart_format` from terminal gives proper output with usage instructions explaining the flags available
Confirmed `~/.pub-cache/bin` is part of my `$PATH`
Restarted Android Studio multiple times to no avail

Application: Android Studio Koala | 2024.1.1
OS: Linux - Arch
Plugin version: 2.0.9
External dart_format version: 1.1.18

**Comment by sdooweloc** [comment]
@eggnstone any advice or ideas here?

**Comment by eggnstone** [comment]
Please try the latest version of the plugin:
https://plugins.jetbrains.com/plugin/21003-dartformat/edit/versions/stable/573377
Does it work now?

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
