### ISSUE TITLE
Unexpected process exit while waiting for connection details from external dart_format.

### ISSUE THREAD

**Issue by varmapradeep** [eggnstone/DartFormatJetbrainsPlugin#8]
Please supply any additional information here, e.g. the source code that caused the error:

```
StdErr: 'dart_format' is not recognized as an internal or external command,
StdErr: operable program or batch file.
```

**Comment by eggnstone** [comment]
- Did you install the dart package dart_format with ```dart pub global activate dart_format```?
- Does calling ```dart_format``` work (i.e, does it start the dart_format program, or still "No such file or directory"?)
- Which operation system do you use?

**Comment by eggnstone** [comment]
@varmapradeep 
Please check the latest version (2.5) of the DartFormat plugin:
https://plugins.jetbrains.com/plugin/21003-dartformat/versions
This one should fix the problem or at least give better diagnostics.

**Comment by eggnstone** [comment]
Please reopen if the error still occurs.
