### ISSUE TITLE
Timeout while waiting for external dart_format.

### ISSUE THREAD

**Issue by Aprcc** [eggnstone/DartFormatJetbrainsPlugin#80]
Please supply any additional information here, e.g. the source code that caused the error:

Origin: FormatAction.formatOrReport/1
OS: Windows 10
Plugin version: 20030108
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
Please update to version 2.0.13 https://plugins.jetbrains.com/plugin/21003-dartformat/versions/stable/573900
and report if it occurs again.

**Comment by midhun000** [comment]
I am using  2.0.13. Getting the same error

**Comment by eggnstone** [comment]
@midhun000 Can you attach the DartFormatPlugin...log and dart_format....log from your temp path please?
It should be in %TEMP% or C:\Temp or /temp or /tmp.

**Comment by eggnstone** [comment]
Please try the latest version (2.0.15).
If it still occurs, then
- exit the IDE
- attached the latest dartformat log files from your temp directory (%TEMP% or C:\Temp or /temp or /tmp)

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
