### ISSUE TITLE
Unexpected process exit while waiting for connection details from external dart_format.

### ISSUE THREAD

**Issue by doudou201703** [eggnstone/DartFormatJetbrainsPlugin#81]
Please supply any additional information here, e.g. the source code that caused the error:

```
StdErr: /Users/xiao/.pub-cache/bin/dart_format: line 8: dart: command not found
Did you install the dart_format package?
Basically just execute this:<pre>dart pub global activate dart_format</pre>
```
OS: Mac OS X
Plugin version: 2.0.15
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
It looks like dart_format was installed but dart cannot be found?
Weird.

Can you start dart_format from the command line?

Please send the DartFormatPlugin*.log and dart_format*.log from your temp path, e.g. /tmp.

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
