### ISSUE TITLE
External dart_format process is dead.

### ISSUE THREAD

**Issue by msk286** [eggnstone/DartFormatJetbrainsPlugin#83]
Please supply any additional information here, e.g. the source code that caused the error:

```
DartFormatException(type=Error, source=Local, message=External dart_format process is dead., cause=null, line=null, column=null)
	at dev.eggnstone.plugins.jetbrains.dartformat.DartFormatException$Companion.localError(DartFormatException.kt:20)
	at dev.eggnstone.plugins.jetbrains.dartformat.DartFormatException$Companion.localError$default(DartFormatException.kt:18)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat.run(ExternalDartFormat.kt:250)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat.access$run(ExternalDartFormat.kt:24)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat$run$1.invokeSuspend(ExternalDartFormat.kt
```
Origin: ExternalDartFormat.run/Exception
OS: Mac OS X
Plugin version: 2.0.16
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
Does restarting the IDE help?

Can you send the logfiles?
dart_format*.log and dartformatplugin*.log in your temp dir.

**Comment by msk286** [comment]
Hi,
Yes, I did it. but still show error message every time I open th IDE.
https://share.cleanshot.com/3DRWNkPGXcRbYy6QB8bL￼
CleanShot 2024-08-24 at 1 .52.58
share.cleanshot.com

**Comment by eggnstone** [comment]
Can you send the logfiles?
dart_format*.log and dartformatplugin*.log in your temp dir.

**Comment by msk286** [comment]
Hi,

I'm sorry for my late response. Please find the log files attached.

Thank you!

Best regards,



￼￼￼

**Comment by eggnstone** [comment]
Please check again. I cannot see any logs.

**Comment by eggnstone** [comment]
Please try the latest version:
https://plugins.jetbrains.com/plugin/21003-dartformat/versions/stable/599098

**Comment by msk286** [comment]
Hello,

Thank you for your email. I wanted to let you know that I have tried the latest version of the plugin you shared and I'm happy to inform you that the issue has been resolved. I am now using it and it's working perfectly. 

Thank you once again for your assistance. Happy coding!

Best regards,
Suhail Kawsara

**Comment by eggnstone** [comment]
@msk286 Thank you for the feedback and your kind review! Happy it finally works!
