### ISSUE TITLE
Cannot run program "dart_format": error=2, No such file or directory

### ISSUE THREAD

**Issue by emmy-omega** [eggnstone/DartFormatJetbrainsPlugin#9]
Please supply any additional information here, e.g. the source code that caused the error:

```
java.io.IOException: Cannot run program "dart_format": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat$run$process$1.invokeSuspend(ExternalDartFormat.kt:120
```
Origin: ExternalDartFormat.run/1

**Comment by eggnstone** [comment]
- Did you install the dart package dart_format with ```dart pub global activate dart_format```?
- Does calling ```dart_format``` work (i.e, does it start the dart_format program, or still "No such file or directory"?)
- Which operation system do you use?

**Comment by eggnstone** [comment]
@emmy-omega 
Please check the latest version (2.5) of the DartFormat plugin:
https://plugins.jetbrains.com/plugin/21003-dartformat/versions
This one should fix the problem or at least give better diagnostics.

**Comment by eggnstone** [comment]
Please reopen if the error still occurs.
