### ISSUE TITLE
Unexpected process exit while waiting for connection details from external dart_format.

### ISSUE THREAD

**Issue by THILLAI1816** [eggnstone/DartFormatJetbrainsPlugin#91]
Please supply any additional information here, e.g. the source code that caused the error:

```
StdErr: 'C:\Users\THILLAI' is not recognized as an internal or external command,
StdErr: operable program or batch file.
Did you install the dart_format package?
Basically just execute this:<pre>dart pub global activate dart_format</pre>
```
OS: Windows 11
Plugin version: 2.0.19
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
Does your username have a space in it?

**Comment by eggnstone** [comment]
I uploaded a fixed version that better handles paths with user names that contains spaces. 
It usually takes 1-2 days to get a new version approved.
Please check the version 2.0.20 and report back.

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
