### ISSUE TITLE
Unexpected process exit while waiting for connection details from external dart_format.

### ISSUE THREAD

**Issue by SaifulislamAhmadzai** [eggnstone/DartFormatJetbrainsPlugin#92]
Please supply any additional information here, e.g. the source code that caused the error:

```
StdOut: Error: Unable to find git in your PATH.
Did you install the dart_format package?
Basically just execute this:<pre>dart pub global activate dart_format</pre>
```
OS: Windows 10
Plugin version: 2.0.9
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
It looks like you are using an old version of the plugin.
Please upgrade to 2.0.20

**Comment by eggnstone** [comment]
Did you install dart and flutter?
It seems that you don't have git installed. I think that's a prerequisite.

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
