### ISSUE TITLE
Failed to start external dart_format: Cannot find the dart_format package: File does not exist at expected location: C:\Users\Le PR ALI 1212\AppData\Local\Pub\Cache\bin\dart_format.bat

### ISSUE THREAD

**Issue by Alipepr** [eggnstone/DartFormatJetbrainsPlugin#95]
Please supply any additional information here, e.g. the source code that caused the error:

OS: Windows 10
Plugin version: 2.0.9
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
It looks like you are using an old version of the plugin.
Please upgrade to 2.0.20

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
